name: Build Executables

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
            version: '0.9.0'
            enable-cache: true
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev
      
      - name: Build executable
        run: |
          uv run pyinstaller --onefile --windowed --name obs-gsheets src/main.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: obs-gsheets-${{ matrix.os }}
          path: dist/*